name = "novamail"
compatibility_date = "2024-01-01"

pages_build_output_dir = "out"

# 环境变量
[vars]
CREEM_API_KEY = "creem_22oMcuzUH4TeWyWVAVjTes"
CREEM_BASE_URL = "https://api.creem.io/v1"
CREEM_WEBHOOK_SECRET = "whsec_5uvCq8f1gQMsqz5rqwdVgZ"
RESEND_API_KEY = "re_HoZby1YY_8DhQswTinqLVqUwFjqHV4V7y"  # Resend API密钥

# Gmail API 配置 (用于注册验证码)
GMAIL_SMTP_USER = "lihongyangnju@gmail.com"  # Gmail邮箱
GMAIL_SMTP_PASSWORD = "zjhk rkmy ysoz dhyi"  # Gmail应用专用密码
# Gmail API 令牌现在在 Cloudflare Dashboard 中配置为 Secrets
# GMAIL_ACCESS_TOKEN = "配置为 Secret"
# GMAIL_REFRESH_TOKEN = "配置为 Secret"
GMAIL_SMTP_HOST = "smtp.gmail.com"
GMAIL_SMTP_PORT = "587"

# Google OAuth 配置
GOOGLE_CLIENT_ID = "3269831923-bu142o4r9b9f29jm8tb0qmumitgu51t9.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"

# ESP导出服务配置
# Mailchimp OAuth (需要配置为 Secrets)
# MAILCHIMP_CLIENT_ID = "配置为 Secret"
# MAILCHIMP_CLIENT_SECRET = "配置为 Secret"
# MAILCHIMP_REDIRECT_URI = "https://your-domain.com/api/mailchimp/callback"

# SendGrid API (需要配置为 Secrets)
# SENDGRID_API_KEY = "配置为 Secret"