name = "novamail"
compatibility_date = "2024-01-01"

pages_build_output_dir = ".next"

# Workers Functions配置
[functions]
directory = "functions"
compatibility_date = "2024-01-01"

# 环境变量
[vars]
CREEM_API_KEY = "creem_22oMcuzUH4TeWyWVAVjTes"
CREEM_BASE_URL = "https://api.creem.com/v1"
CREEM_WEBHOOK_SECRET = "whsec_5uvCq8f1gQMsqz5rqwdVgZ"
